---

- name: checking service status
  hosts: rhel:control
  gather_facts: false
  tasks:
  - name: checking service status
    command: systemctl status "{{ item }}"
    with_items:
    - crond
    - sshd
    register: result
    ignore_errors: yes
  - name: corn process count
    shell: ps -ef |grep -i crond |grep -v grep |wc -l
    register: command_result
    failed_when: "'1' not in command_result.stdout"
